apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: standard
  name: efk
  labels: 
    app: efk
spec:
 persistentVolumeReclaimPolicy: Retain
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
 capacity:
   storage: 10Gi
 nfs:
   path: /storage/efk
   server: 10.0.1.69
 storageClassName: nfs