apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
      name: web
  type: NodePort