apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: standard
  name: jenkins
spec:
 accessModes:
  - ReadWriteOnce
 capacity:
   storage: 10Gi
 nfs:
   path: /storage/jenkins
   server: 10.0.1.66
 persistentVolumeReclaimPolicy: Retain
 volumeMode: Filesystem
 storageClassName: nfs