installCRDs: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<>
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
webhook:
  # Specifies how the service should be handled. Useful if you want to expose the
  # webhook to outside of the cluster. In some cases, the control plane cannot
  # reach internal services.
  serviceType: ClusterIP
  # NodePort, LoadBalancer
  # loadBalancerIP:
  hostNetwork: true
  securePort: 10260