#apiVersion: v1
#kind: Secret
#metadata:
#  name: cert-manager-secret
#  namespace: kube-system
#type: Opaque
#stringData:
#  secret-token: ""
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    email: <email>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - "reines-test.link"
            - "*.reines-test.link"
        dns01:
          route53:
            region: ap-northeast-2
            hostedZoneID: <hostid>
#            role: arn:aws:iam::<>
#            accessKeyID: ""
#            secretAccessKeySecretRef:
#              name: cert-manager-secret
#              key: secret-token

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: le-crt
  namespace: kube-system
spec:
  secretName: tls-certmanager
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: reines-test.link
  dnsNames:
    - reines-test.link
    